import java.util.*;

class LRUCache {

    // Doubly Linked List Node
        class Node {
                int key, value;
                        Node prev, next;
                                Node(int k, int v) {
                                            key = k;
                                                        value = v;
                                                                }
                                                                    }

                                                                        private final int capacity;
                                                                            private final Map<Integer, Node> map;
                                                                                private final Node head, tail; // Dummy nodes for easy operations

                                                                                    public LRUCache(int capacity) {
                                                                                            this.capacity = capacity;
                                                                                                    this.map = new HashMap<>();
                                                                                                            
                                                                                                                    // Initialize dummy head and tail
                                                                                                                            head = new Node(0, 0);
                                                                                                                                    tail = new Node(0, 0);
                                                                                                                                            head.next = tail;
                                                                                                                                                    tail.prev = head;
                                                                                                                                                        }

                                                                                                                                                            public int get(int key) {
                                                                                                                                                                    if (!map.containsKey(key)) {
                                                                                                                                                                                return -1;
                                                                                                                                                                                        }
                                                                                                                                                                                                Node node = map.get(key);
                                                                                                                                                                                                        moveToHead(node); // Recently used, so move to front
                                                                                                                                                                                                                return node.value;
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        public void put(int key, int value) {
                                                                                                                                                                                                                                if (map.containsKey(key)) {
                                                                                                                                                                                                                                            // Update existing node
                                                                                                                                                                                                                                                        Node node = map.get(key);
                                                                                                                                                                                                                                                                    node.value = value;
                                                                                                                                                                                                                                                                                moveToHead(node);
                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                    // Insert new node
                                                                                                                                                                                                                                                                                                                Node newNode = new Node(key, value);
                                                                                                                                                                                                                                                                                                                            map.put(key, newNode);
                                                                                                                                                                                                                                                                                                                                        addToHead(newNode);

                                                                                                                                                                                                                                                                                                                                                    if (map.size() > capacity) {
                                                                                                                                                                                                                                                                                                                                                                    Node lru = removeTail(); // Remove least recently used
                                                                                                                                                                                                                                                                                                                                                                                    map.remove(lru.key);
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                // --- Helper Methods ---

                                                                                                                                                                                                                                                                                                                                                                                                                    // Add new node right after head
                                                                                                                                                                                                                                                                                                                                                                                                                        private void addToHead(Node node) {
                                                                                                                                                                                                                                                                                                                                                                                                                                node.prev = head;
                                                                                                                                                                                                                                                                                                                                                                                                                                        node.next = head.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                head.next.prev = node;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        head.next = node;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Remove node from list
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private void removeNode(Node node) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            node.prev.next = node.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    node.next.prev = node.prev;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Move existing node to head
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void moveToHead(Node node) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        removeNode(node);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addToHead(node);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Remove last node (LRU)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private Node removeTail() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Node node = tail.prev;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            removeNode(node);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return node;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        